gisce/openerp-client-kde

- Koo/Common/Api.py
> Fix kooApi inheritance

- Koo/Fields/Binary/BinaryFieldWidget.py
- Koo/Fields/Image/ImageFieldWidget.py
- Koo/Model/Field.py
- Fixes the load and save of a binary field
> Fixes binary field

- Koo/Model/Record.py
- Enables evaluation of the attrs values for fields
> Enables the interpretation of the attrs  values

- Koo/Model/Field.py
- Koo/Model/Group.py
> Fix *2many

- Koo/Fields/Selection/Selection.py
It fixes the selections widget
So far, selections are broken, so changes are not identified nor showed at UI level.
Fix #16 Selections widget seems broken
> Fix selection widget

- Koo/Fields/Binary/BinaryFieldWidget.py
- Fixest the save of the binary field
> Fixes save binary field

- Koo/Fields/AbstractFieldWidget.py
- Pass docstring sot sphynx format
- Improve docstrings with typing
- To improve the knowladge of the widget and improve the documentation
Related to #31 Docstrings standardization
> Improve Abstract Field Widget docstrings

- tests/test_show_qt5_window.py
- Fixes identation of the `test_show_qt5_window.py`
> Fix identation

- Koo/Fields/Boolean/Boolean.py
- Koo/Fields/CheckBoxFieldWidget/CheckBoxFieldWidget.py
- Koo/Fields/ProgressBar/ProgressBar.py
Some minor fixes to Qt4 deprecated methods
> Removed Qt4 V4 and V2

- Koo/Fields/Boolean/Boolean.py
It fixes the toBool() bug at Boolean field
> Fix toBool

- Koo/Rpc/Rpc.py
Fixes https://github.com/gisce/openerp-client-kde/issues/44
> Fix undefined _ (use gettext)

- Koo/Model/KooModel.py
- Fixes mixed identation of tabs and spaces
> Fix mixed identation

- Koo/Dialogs/SearchDialog.py
- Koo/Fields/OneToMany/OneToMany.py
- Koo/Fields/Reference/ReferenceFieldWidget.py
- Koo/Model/Field.py
- Koo/Model/Group.py
- Koo/Model/Record.py
- Koo/Rpc/Rpc.py
- Koo/Screen/Action.py
- Koo/Screen/Screen.py
- Koo/Search/CustomSearchFormWidget.py
- Modifies the `idModified` of Record to check if has a RecordGroup modified
- Modifes the `get` to get modificated fields from RecordGroup
- Fixes docstrings
- Fixes the action creation
- Fixes usage of reserved words
> Fix 2many save

- Koo/Screen/ScreenDialog.py
> Avoid use reserved words

- Koo/Dialogs/SearchDialog.py
- Koo/Fields/ManyToOne/ManyToOne.py
- Koo/Model/Group.py
- Koo/Model/KooModel.py
- Koo/Screen/Screen.py
- Koo/Search/SearchFormWidget.py
- Makes if the Search dialog selects an element don't raise an exception
- If the user clicks on a empty row of the search dialog the field is cleared
- Fixes https://github.com/gisce/openerp-client-kde/issues/48
> Fix filter 

- Koo/Search/SearchFormWidget.py
- Fixes error max recursion when searches on a SearchDialog and preses intro to submit the search
> Fix max recursion search

- Koo/Screen/ScreenDialog.py
- Fixes https://github.com/gisce/openerp-client-kde/issues/47
> Fix open form

- Koo/Dialogs/SearchDialog.py
- Fixes the refresh of the screen after the values are loaded
- The widget refreshed after lost and get focus
> Fix search widget update

- Koo/Dialogs/FormWidget.py
- Koo/Model/Record.py
- Koo/View/Form/FormView.py
- Fixes the save dialog when there are invalid records on the form
> Fix save dialog

- Koo/Model/Field.py
- Koo/Model/Group.py
- Pep8 code and fix docstrings
> Pep8 and fix docstrings

- Koo/Common/Settings.py
- Fixes the save on .koorc file
> Fix settings save

- Koo/Dialogs/FormWidget.py
- Koo/Dialogs/KooMainWindow.py
- Koo/Dialogs/ServerConfigurationDialog.py
- Koo/Dialogs/TreeWidget.py
- Koo/View/Form/FormView.py
- Koo/View/Tree/TreeView.py
- Koo/koo.py
> Fix koo startup

- Koo/View/Form/FormView.py
- Fixes the load of the koo form from Qgis
> Remove unneeded code

- Koo/Model/Record.py
- Fixes the state when the state value is False
> Fix state 

- Koo/Fields/ManyToMany/ManyToMany.py
- Add dumb method to have save and cancel methods
> Fix Many2Many Widgets

- Koo/Dialogs/TreeWidget.py
- Fixes when user clicks on the user shortcuts
> Fix user shortcuts

- Koo/Model/KooModel.py
> Improve code

- Koo/Model/Record.py
> Fix docstrings record

- .travis.yml
- tests/test.py
- Adds basic tests for records
> Add basic tests for Record

- Koo/Rpc/Rpc.py
> Fix docstrings

- Koo/Model/KooModel.py
- Fixes the set data of the float, text or datetime
- The Qvariant api changes on the Pyqt5
> Fixes the setData of the types float, text or datetime

- Koo/Actions/Wizard.py
- Koo/Dialogs/FormWidget.py
- Koo/Fields/Action/ActionFieldWidget.py
- Koo/Screen/Screen.py
- Fixes the wizard creation adding dumy save and cancel and adding missing datetime on the context
> Fix wizard open

- Koo/Dialogs/FormWidget.py
- Cleanup of the FormWidget:
- Fix Message Box
- Pep8 
- Fix docstrings
- Remove unused vars
- Avoid reserved words
> Improve code of FormWidget

- Koo/Common/WhatsThisEventFilter.py
- Pass docstrings to the sphinx format
> Improve docstrings

- server-modules/koo/koo.py
> Fix miexed spaces and tabs

- Koo/Model/KooModel.py
> Improve code of koomodel

- Koo/Model/Group.py
- Koo/Model/KooModel.py
- Improve code , pep8 and docstrings
> Improve code of groups

- Koo/Model/Field.py
> Improve code of Field

- Koo/Fields/Web/WebFieldWidget.py
- Improve and uncomment web field
> Improve web field

- Koo/Model/Record.py
> Improve code read

- readme.md
> Add installation readme

- Koo/Common/Plugins.py
- Koo/Plugins/__init__.py
- Fixes the scan of the zip files on the plugins directory creating a new function inseted of using hte pluginimport
> Fix the scan of the zip files on the plugins directory 

- Koo/Common/Debug.py
- Koo/Common/Settings.py
- Koo/koo.py
- requirements.txt
- Add sentry suport
- Fixes https://github.com/gisce/openerp-client-kde/issues/82
-  By default Koo have  the function `exceptionHook` that is called when there is an exception to print the message on the stdout
- Adds the startup of Koo on a try/except that captures the exception an reports with sentry
> Add sentry support

- Koo/Fields/Boolean/Boolean.py
> Fix boolean edit

- Koo/Common/EnterEventFilter.py
> Improve code event

- Koo/Common/Common.py
> Improve code common

- Koo/Common/Help.py
> Improve code Help

- Koo/Common/OpenOffice.py
> Improve code OpenOffice

- Koo/Common/Paths.py
> Improve coe Paths

- Koo/Common/Calendar.py
- Remove comment
- Pep8 strings
> Improve code calendar

- Koo/Model/Record.py
This fix issues when testing with VCR
> Sort list of default fields to ensure XML is repeatable

- Koo/Actions/Wizard.py
- Improve docstrings
- Remove unused imports
- Improve code redability
> Improve  wizard code

- Koo/Actions/Actions.py
- Remove unused imports
- Improve docstringrs
- Improve code redability
> Improve code of actions

- Koo/Common/ArrowsEventFilter.py
- Improve docstrings
- Improve code redability
> Improve arrows code

- Koo/Common/CommandLine.py
- Remove unused imports
- Pep8 commends
- Improve code redability
> Improve code command line

- Koo/Fields/Reference/ReferenceFieldWidget.py
- Fix the `search` of the reference field
> Fix the search of reference field

- Koo/Screen/Screen.py
> Fix parameter name

- Koo/Common/Debug.py
- Try to import raven to avoid exceptions if it's not installed
> Improve raven import

- Koo/Rpc/Client.py
- Patches the client to read the defaults before to do the create
> Patch client to use defaults on the create

- Koo/Screen/Screen.py
- Fixes addView parameter from `id` to `ident`(previously renamed)
> Fix addView method

- Koo/Fields/ManyToOne/ManyToOne.py
- Koo/Screen/Screen.py
Dummy PR, it should goes to master directly...
> Fix param name

- Koo/Model/Record.py
- requirements.txt
- setup.py
- Allow set values to a record before save to the ERP. 
- Add support for msgpack communication protocol.
> Allow set before save record function and add msgpack support

- Koo/Rpc/Client.py
Fix create overwrite on client model
> Fix create overwrite on client model

- Koo/Common/Icons.py
- Koo/Dialogs/FormWidget.py
- Koo/Fields/Reference/ReferenceFieldWidget.py
Add improvements for KOO to work with Qgisce
> Improve koo for qgisce

- Koo/Model/Record.py
- Koo/Rpc/Rpc.py
- Added a way to execute a function after save a Record Form.
- Added a way to execute a function if an error is raised on a save Record Form.
- Adapted the way that the RPC errors are handled.
> Improve the KOO for the Qgisce usage

- Koo/Fields/Button/ButtonFieldWidget.py
- Koo/Model/Record.py
- Improve error handling on wizards and buttons actions.
- Don't fill geom if the element don't have a field named geom.
> Improve error handling on wizards and buttons actions

- Koo/Fields/Reference/ReferenceFieldWidget.py
Pass dialog to the new dialog of a reference field.
> Pass dialog to the new dialog of a reference field.

- Koo/Common/Help.py
- Koo/Dialogs/FormWidget.py
- Koo/Dialogs/FullTextSearchDialog.py
- Koo/Dialogs/WebWidget.py
- Koo/Fields/Web/WebFieldWidget.py
- Koo/Fields/Web/__init__.py
- Koo/koo.py
- Koo/ui/full_text_search.ui
- Koo/ui/web.ui
- Koo/ui/webcontainer.ui
- requirements.txt
Reverts gisce/openerp-client-kde#145
> Revert "Use QWebEngine as QWeb is deprecated after 5.5"

- Koo/Model/Record.py
Execute the after_save_function even if there are no changes.
> Execute the after_save_function even if there are no changes.

- Koo/Dialogs/SearchOnlyDialog.py
- Koo/ui/win_search_only.ui
Add a new search only dialog without the new button.
> Add new search only dialog.
